global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files: [alerts.yml]

scrape_configs:
  - job_name: triton
    static_configs: [{targets: ["triton:8002"]}]
  - job_name: dcgm
    static_configs: [{targets: ["dcgm-exporter:9400"]}]
